import { NextPage } from "next"
import Head from "next/head"
import Nav from "../components/Nav"

import "../sdk/staking_pool"

const Index: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Only1 - Testing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      
      <div className="container">
        <p>Hello There</p>
      </div>

    </div>
  )
}

export default Index
