import { NextPage } from "next"
import Head from "next/head"
import Nav from "../components/Nav"

const Index: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
    </div>
  )
}

export default Index
